trigger:
- master

pool: ansiblePool

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: '$(Build.SourcesDirectory)/ansible/playbook.yml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: '$(Build.SourcesDirectory)/ansible/hosts'